# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:  
  buildConfiguration: 'Release'

steps:
  
  #install .net SDK

- task: UseDotNet@2
  displayName: 'Install .net SDK'
  inputs:
     packageType: 'sdk'
     version: '9.0.x'
     
#restore NuGet Pckages
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

#Build Solution
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

#run unit tests
- task: DotNetCoreCLI@2
  displayName: 'Run Test'
  inputs:
    command: test
    projects: '**/*Test.csproj'
    arguments:  '--configuration $(buildConfiguration) --no-build'
    publishTestResults: true

#publish web api
- task: DotNetCoreCLI@2
  displayName: 'Publish web api'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

#publish art
- task: PublishBuildArtifacts@1
  displayName: 'Publsih Artifiacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: Container

